/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author 48faraaz
 */
public class InventoryGUI extends javax.swing.JFrame {

    /**
     * Creates new form InventoryGUI2
     */
    public InventoryGUI() {
        initComponents();
    }
    
    public InventoryGUI(String tipe, String idSupp) {
        initComponents();
        
        if(tipe == "staff") {
            
        } else {
            edtSupplierInv.setEnabled(false);
            edtSupplierInv.setText(tipe);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnStockAktif = new javax.swing.JButton();
        btnStockPending = new javax.swing.JButton();
        pnlUtama = new javax.swing.JPanel();
        pnlStockAktif = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        edtNamaInv = new javax.swing.JTextField();
        edtJumlahInv = new javax.swing.JTextField();
        edtHargaInv = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        edtSupplierInv = new javax.swing.JTextField();
        btnTambahInv = new javax.swing.JButton();
        edtTanggal = new com.toedter.calendar.JDateChooser();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableInventory = new javax.swing.JTable();
        pnlStockPending = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnStockAktif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/files-o.png"))); // NOI18N
        btnStockAktif.setText("Stock Aktif");
        btnStockAktif.setFocusable(false);
        btnStockAktif.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStockAktif.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnStockAktif);

        btnStockPending.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/file.png"))); // NOI18N
        btnStockPending.setText("Stock Pending");
        btnStockPending.setFocusable(false);
        btnStockPending.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStockPending.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnStockPending);

        pnlUtama.setLayout(new java.awt.CardLayout());

        pnlStockAktif.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Stock yang Tersisa");
        pnlStockAktif.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 13, -1, -1));

        jLabel8.setText("Nama Barang");
        pnlStockAktif.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 192, -1, -1));

        jLabel9.setText("Kuantitas");
        pnlStockAktif.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 221, -1, -1));

        jLabel10.setText("Harga");
        pnlStockAktif.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 250, -1, -1));

        jLabel11.setText("Tanggal");
        pnlStockAktif.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 276, -1, -1));
        pnlStockAktif.add(edtNamaInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 189, 177, -1));
        pnlStockAktif.add(edtJumlahInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 218, 177, -1));
        pnlStockAktif.add(edtHargaInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 247, 177, -1));

        jLabel12.setText("Supplier");
        pnlStockAktif.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 308, -1, -1));
        pnlStockAktif.add(edtSupplierInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 305, 177, -1));

        btnTambahInv.setText("Tambah");
        btnTambahInv.setActionCommand("");
        btnTambahInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahInvActionPerformed(evt);
            }
        });
        pnlStockAktif.add(btnTambahInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 334, -1, -1));

        edtTanggal.setDateFormatString("yyyy-MM-dd");
        pnlStockAktif.add(edtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 276, 177, -1));

        btnDelete.setText("Delete");
        pnlStockAktif.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 334, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        pnlStockAktif.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 334, -1, -1));

        tableInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "name", "stock", "price", "supplier"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableInventory);

        pnlStockAktif.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 48, 556, 128));

        pnlUtama.add(pnlStockAktif, "cardStockAktif");

        javax.swing.GroupLayout pnlStockPendingLayout = new javax.swing.GroupLayout(pnlStockPending);
        pnlStockPending.setLayout(pnlStockPendingLayout);
        pnlStockPendingLayout.setHorizontalGroup(
            pnlStockPendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        pnlStockPendingLayout.setVerticalGroup(
            pnlStockPendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        pnlUtama.add(pnlStockPending, "cardStockPending");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnTambahInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahInvActionPerformed
        
    }//GEN-LAST:event_btnTambahInvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnStockAktif;
    private javax.swing.JButton btnStockPending;
    private javax.swing.JButton btnTambahInv;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField edtHargaInv;
    private javax.swing.JTextField edtJumlahInv;
    private javax.swing.JTextField edtNamaInv;
    private javax.swing.JTextField edtSupplierInv;
    private com.toedter.calendar.JDateChooser edtTanggal;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel pnlStockAktif;
    private javax.swing.JPanel pnlStockPending;
    private javax.swing.JPanel pnlUtama;
    private javax.swing.JTable tableInventory;
    // End of variables declaration//GEN-END:variables
}
