/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Connection.ConnectionManager;
import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author 48faraaz
 */
public class RadiologiGUI extends javax.swing.JFrame {

    /**
     * Creates new form GuiRadiologi
     */
    public RadiologiGUI() {
        initComponents();
        getPasienListToComboBox();
        getDokterListToComboBox();
    }
    
    private void getPasienListToComboBox() {
        String query = "select ktp from pasien";
        ConnectionManager conMan = new ConnectionManager();
        Connection conn = conMan.LogOn();
        try {
            Statement stm = conn.createStatement();
            ResultSet rs = stm.executeQuery(query);
            while(rs.next()) {
                boxPasianMain.addItem(rs.getString("ktp"));
            }
        } catch (SQLException ex) {
            //Logger.getLogger(ExecuteInventory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void getDokterListToComboBox() {
        String query = "select ktp from dokter";
        ConnectionManager conMan = new ConnectionManager();
        Connection conn = conMan.LogOn();
        try {
            Statement stm = conn.createStatement();
            ResultSet rs = stm.executeQuery(query);
            while(rs.next()) {
                boxDosenMain.addItem(rs.getString("ktp"));
            }
        } catch (SQLException ex) {
            //Logger.getLogger(ExecuteInventory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edtTotalMain = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        boxPasianMain = new javax.swing.JComboBox();
        boxDosenMain = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePemeriksaanMain = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableFilmMain = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        edtNoBuktiMain = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        edtBiayaMain = new javax.swing.JTextField();
        btnSimpanMain = new javax.swing.JButton();
        btnTutupMain = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        edtCatatanMain = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        edtTanggal = new com.toedter.calendar.JDateChooser();
        btnSimpanMain1 = new javax.swing.JButton();
        btnSimpanMain2 = new javax.swing.JButton();
        btnSimpanMain3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tanggal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 60, -1, -1));

        jLabel2.setText("No. Bukti");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 89, -1, -1));

        edtTotalMain.setName("EdtBukti"); // NOI18N
        getContentPane().add(edtTotalMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 120, -1));

        jLabel4.setText("Pasien");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 54, -1, -1));

        jLabel5.setText("Pemeriksa");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 86, -1, -1));

        boxPasianMain.setName("ComboPasien"); // NOI18N
        getContentPane().add(boxPasianMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 48, 215, -1));

        boxDosenMain.setName("ComboPemeriksa"); // NOI18N
        getContentPane().add(boxDosenMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 83, 215, -1));

        jLabel6.setText("Pemeriksaan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        tablePemeriksaanMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Tarif"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablePemeriksaanMain.setName("TblPemeriksaan"); // NOI18N
        jScrollPane1.setViewportView(tablePemeriksaanMain);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 573, 105));

        jLabel7.setText("Film Radiologi");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        tableFilmMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Satuan", "Kuantitas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableFilmMain.setName("TblRadiologi"); // NOI18N
        jScrollPane2.setViewportView(tableFilmMain);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 573, 105));

        jLabel8.setText("Total Film");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));

        jLabel9.setText("Biaya");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));

        edtNoBuktiMain.setText("otomatis");
        edtNoBuktiMain.setEnabled(false);
        edtNoBuktiMain.setName("EdtBukti"); // NOI18N
        getContentPane().add(edtNoBuktiMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 83, 181, -1));

        jLabel10.setText("lembar");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, -1, -1));

        edtBiayaMain.setName("EdtBukti"); // NOI18N
        getContentPane().add(edtBiayaMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 172, -1));

        btnSimpanMain.setText("Simpan");
        btnSimpanMain.setName("BtnSimpan"); // NOI18N
        getContentPane().add(btnSimpanMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, -1, -1));

        btnTutupMain.setText("Reset");
        btnTutupMain.setName("BtnTutup"); // NOI18N
        getContentPane().add(btnTutupMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, -1, -1));

        jLabel11.setText("Catatan Dokter");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        edtCatatanMain.setColumns(20);
        edtCatatanMain.setRows(5);
        jScrollPane3.setViewportView(edtCatatanMain);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 308, 90));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Radiologi Rs. Kasih Sayang Wibu");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 13, -1, -1));

        edtTanggal.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(edtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 54, 181, -1));

        btnSimpanMain1.setText("Delete");
        btnSimpanMain1.setName("BtnSimpan"); // NOI18N
        getContentPane().add(btnSimpanMain1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        btnSimpanMain2.setText("Tambah");
        btnSimpanMain2.setName("BtnSimpan"); // NOI18N
        getContentPane().add(btnSimpanMain2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        btnSimpanMain3.setText("Update");
        btnSimpanMain3.setName("BtnSimpan"); // NOI18N
        getContentPane().add(btnSimpanMain3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadiologiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadiologiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadiologiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadiologiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadiologiGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox boxDosenMain;
    private javax.swing.JComboBox boxPasianMain;
    private javax.swing.JButton btnSimpanMain;
    private javax.swing.JButton btnSimpanMain1;
    private javax.swing.JButton btnSimpanMain2;
    private javax.swing.JButton btnSimpanMain3;
    private javax.swing.JButton btnTutupMain;
    private javax.swing.JTextField edtBiayaMain;
    private javax.swing.JTextArea edtCatatanMain;
    private javax.swing.JTextField edtNoBuktiMain;
    private com.toedter.calendar.JDateChooser edtTanggal;
    private javax.swing.JTextField edtTotalMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tableFilmMain;
    private javax.swing.JTable tablePemeriksaanMain;
    // End of variables declaration//GEN-END:variables
}
