/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;

/**
 *
 * @author 48faraaz
 */
public class TambahPegawaiGUI extends javax.swing.JFrame {

    /**
     * Creates new form TambahPegawaiGUI
     */
    public TambahPegawaiGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnDokter = new javax.swing.JButton();
        btnSuster = new javax.swing.JButton();
        btnStaff = new javax.swing.JButton();
        btnSupplier = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        pnlDokter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDokter = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edtKtpDokter = new javax.swing.JTextField();
        edtNamaDokter = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        edtAlamatDokter = new javax.swing.JTextArea();
        edtHpDokter = new javax.swing.JTextField();
        edtKelaminDokter = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnTambahDokter = new javax.swing.JButton();
        btnDeleteDokter = new javax.swing.JButton();
        btnUpdateDokter = new javax.swing.JButton();
        pnlSuster = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDokter1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        edtKtpSuster = new javax.swing.JTextField();
        edtNamaSuster = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        edtAlamatSuster = new javax.swing.JTextArea();
        edtHpSuster = new javax.swing.JTextField();
        edtKelaminSuster = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnTambahSuster = new javax.swing.JButton();
        btnDeleteSuster = new javax.swing.JButton();
        btnUpdateSuster = new javax.swing.JButton();
        pnlStaff = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblDokter2 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        edtKtpStaff = new javax.swing.JTextField();
        edtNamaStaff = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        edtAlamatStaff = new javax.swing.JTextArea();
        edtHpStaff = new javax.swing.JTextField();
        edtKelaminStaff = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnTambahStaff = new javax.swing.JButton();
        btnDeleteStaff = new javax.swing.JButton();
        btnUpdateStaff = new javax.swing.JButton();
        pnlSupplier = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblDokter3 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnIdSupplier = new javax.swing.JTextField();
        btnNamaSupplier = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        btnTambahSupplier = new javax.swing.JButton();
        btnDeleteSupplier = new javax.swing.JButton();
        btnUpdateSupplier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/user-md.png"))); // NOI18N
        btnDokter.setText("Dokter");
        btnDokter.setFocusable(false);
        btnDokter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDokter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDokterActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDokter);

        btnSuster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/user-o.png"))); // NOI18N
        btnSuster.setText("Suster");
        btnSuster.setFocusable(false);
        btnSuster.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSuster.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSuster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSusterActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSuster);

        btnStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/user.png"))); // NOI18N
        btnStaff.setText("Staff");
        btnStaff.setFocusable(false);
        btnStaff.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStaff.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffActionPerformed(evt);
            }
        });
        jToolBar1.add(btnStaff);

        btnSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/user-plus.png"))); // NOI18N
        btnSupplier.setText("Supplier");
        btnSupplier.setFocusable(false);
        btnSupplier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSupplier.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSupplier);

        mainPanel.setLayout(new java.awt.CardLayout());

        pnlDokter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ktp", "nama", "alamat", "hp", "kelamin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDokter);
        if (tblDokter.getColumnModel().getColumnCount() > 0) {
            tblDokter.getColumnModel().getColumn(2).setHeaderValue("alamat");
            tblDokter.getColumnModel().getColumn(3).setHeaderValue("hp");
            tblDokter.getColumnModel().getColumn(4).setHeaderValue("kelamin");
        }

        pnlDokter.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 730, 140));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Data Dokter");
        pnlDokter.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel2.setText("KTP");
        pnlDokter.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        pnlDokter.add(edtKtpDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 200, -1));
        pnlDokter.add(edtNamaDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 200, -1));

        edtAlamatDokter.setColumns(20);
        edtAlamatDokter.setRows(5);
        jScrollPane2.setViewportView(edtAlamatDokter);

        pnlDokter.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 200, 70));
        pnlDokter.add(edtHpDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 200, -1));

        edtKelaminDokter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "l", "w" }));
        pnlDokter.add(edtKelaminDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 200, -1));

        jLabel3.setText("Nama");
        pnlDokter.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel4.setText("Alamat");
        pnlDokter.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel5.setText("HP");
        pnlDokter.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel6.setText("Kelamin");
        pnlDokter.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, 20));

        btnTambahDokter.setText("Tambah");
        pnlDokter.add(btnTambahDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        btnDeleteDokter.setText("Delete");
        pnlDokter.add(btnDeleteDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));

        btnUpdateDokter.setText("Update");
        pnlDokter.add(btnUpdateDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        mainPanel.add(pnlDokter, "cardDokter");

        pnlSuster.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDokter1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ktp", "nama", "alamat", "hp", "kelamin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblDokter1);
        if (tblDokter1.getColumnModel().getColumnCount() > 0) {
            tblDokter1.getColumnModel().getColumn(2).setHeaderValue("alamat");
            tblDokter1.getColumnModel().getColumn(3).setHeaderValue("hp");
            tblDokter1.getColumnModel().getColumn(4).setHeaderValue("kelamin");
        }

        pnlSuster.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 730, 140));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Data Suster");
        pnlSuster.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel8.setText("KTP");
        pnlSuster.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        pnlSuster.add(edtKtpSuster, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 200, -1));
        pnlSuster.add(edtNamaSuster, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 200, -1));

        edtAlamatSuster.setColumns(20);
        edtAlamatSuster.setRows(5);
        jScrollPane4.setViewportView(edtAlamatSuster);

        pnlSuster.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 200, 70));
        pnlSuster.add(edtHpSuster, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 200, -1));

        edtKelaminSuster.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "l", "w" }));
        pnlSuster.add(edtKelaminSuster, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 200, -1));

        jLabel9.setText("Nama");
        pnlSuster.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel10.setText("Alamat");
        pnlSuster.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel11.setText("HP");
        pnlSuster.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel12.setText("Kelamin");
        pnlSuster.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, 20));

        btnTambahSuster.setText("Tambah");
        pnlSuster.add(btnTambahSuster, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        btnDeleteSuster.setText("Delete");
        pnlSuster.add(btnDeleteSuster, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));

        btnUpdateSuster.setText("Update");
        pnlSuster.add(btnUpdateSuster, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        mainPanel.add(pnlSuster, "cardSuster");

        pnlStaff.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDokter2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ktp", "nama", "alamat", "hp", "kelamin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblDokter2);
        if (tblDokter2.getColumnModel().getColumnCount() > 0) {
            tblDokter2.getColumnModel().getColumn(2).setHeaderValue("alamat");
            tblDokter2.getColumnModel().getColumn(3).setHeaderValue("hp");
            tblDokter2.getColumnModel().getColumn(4).setHeaderValue("kelamin");
        }

        pnlStaff.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 730, 140));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Data Staff");
        pnlStaff.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel14.setText("KTP");
        pnlStaff.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        pnlStaff.add(edtKtpStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 200, -1));
        pnlStaff.add(edtNamaStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 200, -1));

        edtAlamatStaff.setColumns(20);
        edtAlamatStaff.setRows(5);
        jScrollPane6.setViewportView(edtAlamatStaff);

        pnlStaff.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 200, 70));
        pnlStaff.add(edtHpStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 200, -1));

        edtKelaminStaff.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "l", "w" }));
        pnlStaff.add(edtKelaminStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 200, -1));

        jLabel15.setText("Nama");
        pnlStaff.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel16.setText("Alamat");
        pnlStaff.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel17.setText("HP");
        pnlStaff.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel18.setText("Kelamin");
        pnlStaff.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, 20));

        btnTambahStaff.setText("Tambah");
        pnlStaff.add(btnTambahStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        btnDeleteStaff.setText("Delete");
        pnlStaff.add(btnDeleteStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));

        btnUpdateStaff.setText("Update");
        pnlStaff.add(btnUpdateStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        mainPanel.add(pnlStaff, "cardStaff");

        pnlSupplier.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDokter3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "nama"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tblDokter3);

        pnlSupplier.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 730, 140));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Data Supplier");
        pnlSupplier.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel20.setText("ID");
        pnlSupplier.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        pnlSupplier.add(btnIdSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 200, -1));
        pnlSupplier.add(btnNamaSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 200, -1));

        jLabel21.setText("Nama");
        pnlSupplier.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        btnTambahSupplier.setText("Tambah");
        pnlSupplier.add(btnTambahSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        btnDeleteSupplier.setText("Delete");
        pnlSupplier.add(btnDeleteSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        btnUpdateSupplier.setText("Update");
        pnlSupplier.add(btnUpdateSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        mainPanel.add(pnlSupplier, "cardSupplier");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDokterActionPerformed
        cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "cardDokter");
    }//GEN-LAST:event_btnDokterActionPerformed

    private void btnSusterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSusterActionPerformed
        cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "cardSuster");
    }//GEN-LAST:event_btnSusterActionPerformed

    private void btnStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffActionPerformed
        cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "cardStaff");
    }//GEN-LAST:event_btnStaffActionPerformed

    private void btnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierActionPerformed
        cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "cardSupplier");
    }//GEN-LAST:event_btnSupplierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahPegawaiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahPegawaiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahPegawaiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahPegawaiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahPegawaiGUI().setVisible(true);
            }
        });
    }

    private CardLayout cl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteDokter;
    private javax.swing.JButton btnDeleteStaff;
    private javax.swing.JButton btnDeleteSupplier;
    private javax.swing.JButton btnDeleteSuster;
    private javax.swing.JButton btnDokter;
    private javax.swing.JTextField btnIdSupplier;
    private javax.swing.JTextField btnNamaSupplier;
    private javax.swing.JButton btnStaff;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JButton btnSuster;
    private javax.swing.JButton btnTambahDokter;
    private javax.swing.JButton btnTambahStaff;
    private javax.swing.JButton btnTambahSupplier;
    private javax.swing.JButton btnTambahSuster;
    private javax.swing.JButton btnUpdateDokter;
    private javax.swing.JButton btnUpdateStaff;
    private javax.swing.JButton btnUpdateSupplier;
    private javax.swing.JButton btnUpdateSuster;
    private javax.swing.JTextArea edtAlamatDokter;
    private javax.swing.JTextArea edtAlamatStaff;
    private javax.swing.JTextArea edtAlamatSuster;
    private javax.swing.JTextField edtHpDokter;
    private javax.swing.JTextField edtHpStaff;
    private javax.swing.JTextField edtHpSuster;
    private javax.swing.JComboBox edtKelaminDokter;
    private javax.swing.JComboBox edtKelaminStaff;
    private javax.swing.JComboBox edtKelaminSuster;
    private javax.swing.JTextField edtKtpDokter;
    private javax.swing.JTextField edtKtpStaff;
    private javax.swing.JTextField edtKtpSuster;
    private javax.swing.JTextField edtNamaDokter;
    private javax.swing.JTextField edtNamaStaff;
    private javax.swing.JTextField edtNamaSuster;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pnlDokter;
    private javax.swing.JPanel pnlStaff;
    private javax.swing.JPanel pnlSupplier;
    private javax.swing.JPanel pnlSuster;
    private javax.swing.JTable tblDokter;
    private javax.swing.JTable tblDokter1;
    private javax.swing.JTable tblDokter2;
    private javax.swing.JTable tblDokter3;
    // End of variables declaration//GEN-END:variables
}
